// node build.js  →  dist/  (+ functions/_catalog.js)
const fs = require('fs'), path = require('path');
const D = require('./src/data.js'), S = D.site;
const OUT = path.join(__dirname, 'dist');
const eur = n => n.toFixed(2).replace('.', ',') + ' EUR';
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const img = (f, w = 1200) => `${S.cdn}${f}&width=${w}`;
const srcset = f => [400, 700, 1000, 1400].map(w => `${img(f, w)} ${w}w`).join(', ');
const md = s => esc(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
const count = t => D.products.filter(p => p.tags.includes(t)).length;
const write = (rel, html) => { const f = path.join(OUT, rel); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, html); };
const ld = o => `<script type="application/ld+json">${JSON.stringify(o)}</script>`;
const ORG = { '@type': 'Organization', '@id': S.url + '/#org', name: S.name, alternateName: S.short, url: S.url, logo: S.url + '/favicon.svg', email: S.email, foundingDate: S.founded, address: { '@type': 'PostalAddress', addressLocality: S.locality, addressRegion: S.region, addressCountry: S.country }, sameAs: [S.instagram, S.tiktok], areaServed: ['IE', 'GB', 'EU'] };
const crumbs = items => ({ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: items.map((c, i) => ({ '@type': 'ListItem', position: i + 1, name: c[0], item: S.url + c[1] })) });
const faqLd = list => ({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: list.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) });
const clientData = JSON.stringify({ cdn: S.cdn, freeShip: S.freeShip, cutoffHour: S.cutoffHour, welcomeCode: S.welcomeCode, products: D.products.map(p => ({ id: p.id, name: p.name, price: p.price, images: p.images, tags: p.tags, sizes: p.sizes, stock: p.stock, fit: p.fit, pairs: p.pairs })) });
const SIZE_TABLE = [['XS', 54, 66], ['S', 57, 68], ['M', 60, 70], ['L', 63, 72], ['XL', 66, 74], ['2XL', 69, 76]];
const sizeTable = () => `<table><tr><th>Size</th><th>Chest cm</th><th>Length cm</th></tr>${SIZE_TABLE.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table>`;
const fmtDate = d => new Date(d).toLocaleDateString('en-IE', { day: 'numeric', month: 'short', year: 'numeric' });

fs.writeFileSync(path.join(__dirname, 'functions/_catalog.js'), `// GENERATED by build.js from src/data.js — do not edit\nexport const FREE_SHIP_CENTS = ${Math.round(S.freeShip * 100)};\nexport const SHIP_IE_CENTS = ${Math.round(S.shipIE * 100)};\nexport const SHIP_EU_CENTS = ${Math.round(S.shipEU * 100)};\nexport const CATALOG = ${JSON.stringify(Object.fromEntries(D.products.map(p => [p.id, { name: p.name, price: Math.round(p.price * 100), sizes: p.sizes, stock: p.stock || {}, image: img(p.images[0], 600) }])), null, 1)};\n`);

/* ---------- shell ---------- */
const NAV = [['New in', '/collections/top-picks/', 'acc'], ['The Jersey', '/products/ht-jersey/'], ['Hoodies', '/collections/hoodies/'], ['Outerwear', '/collections/outerwear/'], ['Pants', '/collections/pants/'], ['Sale', '/collections/clearance/'], ['Journal', '/journal/']];
const CHIPS = [['New in', '/collections/top-picks/', 'acc'], ['Shop all', '/shop/'], ['Jersey', '/products/ht-jersey/'], ['Hoodies', '/collections/hoodies/'], ['Outerwear', '/collections/outerwear/'], ['Pants', '/collections/pants/'], ['Sale', '/collections/clearance/'], ['Journal', '/journal/']];
const quizModal = () => `<div class="modal" id="quizModal" role="dialog" aria-label="Fit quiz"><div class="box quiz" id="quiz"><button class="close" id="closeQuiz" aria-label="Close">×</button><h2>Fit quiz</h2><div class="step" id="qstep"></div>
<div class="q on"><p>What size do you usually wear?</p><div class="opts" data-k="size">${['XS', 'S', 'M', 'L', 'XL', '2XL'].map(s => `<button data-v="${s}">${s}</button>`).join('')}</div></div>
<div class="q"><p>Do you always wear that size?</p><div class="opts" data-k="usual"><button data-v="-1">No, I sometimes size down</button><button data-v="0">Yes</button><button data-v="1">No, I sometimes size up</button></div></div>
<div class="q"><p>How would you describe your build?</p><div class="opts" data-k="build"><button data-v="-0.5">Slim</button><button data-v="0">Average</button><button data-v="0.5">Broad</button></div><p>How tall are you? <span class="mute" id="qhv">178 cm</span></p><input type="range" id="qh" min="150" max="205" value="178"></div>
<div class="q"><p>How do you like it to fit?</p><div class="opts" data-k="pref"><button data-v="-1">Fitted</button><button data-v="0">True to size</button><button data-v="1">Loose</button></div></div>
<div class="q"><div class="res" id="qres"></div><p class="mute" style="font-size:12px;margin-top:10px">We'll remember this on every product page. <button id="qretake" style="text-decoration:underline">Retake</button></p></div>
<div class="nav"><button id="qback" class="lnk">Back</button><button id="qnext" class="btn">Next</button></div></div></div>`;
function shell({ title, desc, url, body, jsonld = [], ogImage, type = 'website', recent = true, chips = true }) {
  const canon = S.url + url;
  return `<!DOCTYPE html>
<html lang="en-IE">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${canon}">
<link rel="alternate" hreflang="en-IE" href="${canon}"><link rel="alternate" hreflang="en" href="${canon}"><link rel="alternate" hreflang="x-default" href="${canon}">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
<meta name="geo.region" content="IE-WX"><meta name="geo.placename" content="Wexford, Ireland">
<meta property="og:site_name" content="${esc(S.short)}"><meta property="og:locale" content="en_IE"><meta property="og:type" content="${type}">
<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canon}">
<meta property="og:image" content="${ogImage || img(D.products[0].images[0], 1200)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="1200">
<meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#ffffff">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="preconnect" href="${new URL(S.cdn).origin}">
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/site.css">
${ld({ '@context': 'https://schema.org', '@graph': [ORG, { '@type': 'WebSite', '@id': S.url + '/#site', url: S.url, name: S.name, publisher: { '@id': S.url + '/#org' }, inLanguage: 'en-IE', potentialAction: { '@type': 'SearchAction', target: `${S.url}/shop/?q={search_term_string}`, 'query-input': 'required name=search_term_string' } }] })}
${jsonld.map(ld).join('\n')}
</head>
<body>
<a class="sr" href="#main">Skip to content</a>
<div class="ticker" aria-hidden="true"><div>${S.announce.concat(S.announce).map(a => `<span>${esc(a)}</span>`).join('')}</div></div>
<header class="site">
  <div class="wrap nav">
    <button class="burger" id="burger" aria-label="Open menu"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 7h18M3 12h18M3 17h18"/></svg></button>
    <nav class="menu" aria-label="Main">${NAV.slice(0, 4).map(n => `<a href="${n[1]}" class="${n[2] || ''}"${n[1] === url ? ' aria-current="page"' : ''}>${n[0]}</a>`).join('')}</nav>
    <a class="brand" href="/" aria-label="${esc(S.name)} home">Humble Times<sup>®</sup></a>
    <div class="icons"><nav class="menu" aria-label="Secondary">${NAV.slice(4).map(n => `<a href="${n[1]}"${n[1] === url ? ' aria-current="page"' : ''}>${n[0]}</a>`).join('')}</nav>
      <button id="searchBtn" aria-label="Search">Search</button>
      <button id="cartBtn" aria-label="Open bag">Bag <span class="cart-count" id="cartCount">0</span></button></div>
  </div>
</header>
${chips ? `<nav class="chips" aria-label="Categories">${CHIPS.map(c => `<a href="${c[1]}" class="${c[2] || ''}"${c[1] === url ? ' aria-current="page"' : ''}>${c[0]}</a>`).join('')}</nav>` : ''}
<nav class="mnav" id="mobileNav" aria-label="Mobile"><button class="close" id="closeNav" aria-label="Close menu">×</button><a href="/shop/">Shop all</a>${NAV.map(n => `<a href="${n[1]}" class="${n[2] || ''}">${n[0]}</a>`).join('')}<div class="small" style="margin-top:20px"><a href="/about/">About</a><a href="/shipping/">Delivery</a><a href="/returns/">Returns</a><a href="/faq/">FAQ</a><a href="/contact/">Contact</a></div></nav>
<main id="main">${body}</main>
${recent ? `<section class="sec" id="recent"><div class="wrap sh"><h2>Recently viewed</h2></div><div class="grid row"></div></section>` : ''}
<footer class="site"><div class="wrap">
  <div class="foot">
    <div><h4>Shop</h4><a href="/collections/top-picks/">New in</a><a href="/shop/">Shop all</a><a href="/collections/hoodies/">Hoodies</a><a href="/collections/outerwear/">Outerwear</a><a href="/collections/pants/">Pants</a><a href="/collections/clearance/">Sale</a></div>
    <div><h4>Support</h4><a href="/faq/">FAQ</a><a href="/shipping/">Shipping policy</a><a href="/returns/">Returns &amp; exchanges</a><a href="/size-guide/">Size guide</a><a href="#" data-quiz>Fit quiz</a><a href="/contact/">Contact</a></div>
    <div><h4>Company</h4><a href="/about/">About</a><a href="/journal/">Journal</a><a href="/privacy/">Privacy policy</a><a href="/terms/">Terms &amp; conditions</a></div>
    <div><h4>Social</h4><a href="${S.instagram}" target="_blank" rel="noopener">Instagram</a><a href="${S.tiktok}" target="_blank" rel="noopener">TikTok</a><h4 style="margin-top:18px">Contact</h4><address>${esc(S.name)}<br>${esc(S.locality)}, Ireland<br><a href="mailto:${S.email}" style="display:inline;padding:0">${S.email}</a></address></div>
  </div>
  <div class="foot-bottom"><span class="brand">Humble Times<sup>®</sup> &nbsp;<span class="mute" style="font-weight:400;letter-spacing:.08em">Everyday Irish streetwear</span></span><span>Ireland · EUR · VAT included</span><span class="pay"><span>VISA</span><span>MC</span><span>APPLE PAY</span><span>G PAY</span><span>REVOLUT</span></span><span>© ${new Date().getFullYear()} ${esc(S.name)}</span></div>
</div></footer>
<div class="veil" id="veil"></div>
<aside class="drawer" id="drawer" aria-label="Shopping bag" aria-hidden="true"><div class="drawer-head"><h2>Shopping bag</h2><button id="closeCart" aria-label="Close bag">×</button></div><div class="lines" id="lines"></div><div class="drawer-foot" id="drawerFoot"></div></aside>
<div class="sheet" id="sheet" role="dialog" aria-label="Choose a size"></div>
<div class="modal" id="modal" role="dialog" aria-label="Size guide"><div class="box"><button class="close" id="closeModal" aria-label="Close">×</button><h2>Size guide</h2><p class="mute" style="font-size:12px">Garment measurements, laid flat. All fits are relaxed — size down for a closer fit.</p>${sizeTable()}<p style="font-size:12px"><a href="#" class="lnk" data-quiz>Not sure? Take the fit quiz</a></p></div></div>
${quizModal()}
<div class="search" id="search"><button class="close" id="closeSearch" aria-label="Close search">×</button><label class="sr" for="q">Search</label><input id="q" type="search" placeholder="Search" autocomplete="off"><div class="pops"><span class="lab mute">Popular</span>${['hoodie', 'jersey', 'windbreaker', 'joggers', 'sale'].map(t => `<button>${t}</button>`).join('')}</div><div class="grid" id="sres"></div></div>
<div class="pop" id="pop"><button class="x" id="popX" aria-label="Close">×</button><div><b>10% off your first order</b><p>Drops, restocks and early access. No spam.</p><form id="popForm"><label class="sr" for="pe">Email</label><input id="pe" name="email" type="email" required placeholder="Email address"><button type="submit">Get 10%</button></form></div></div>
<div class="toast" id="toast" role="status"></div>
<script>window.HT=${clientData}</script>
<script src="/site.js" defer></script>
</body></html>`;
}

/* ---------- components ---------- */
const priceHtml = p => `<span class="price${p.was ? ' on' : ''}">${p.was ? `<s>${eur(p.was)}</s>` : ''}${eur(p.price)}</span>`;
const totalStock = p => p.stock ? Object.values(p.stock).reduce((a, b) => a + b, 0) : 99;
const card = (p, i = 0) => `<article class="card" data-id="${p.id}" data-sizes="${p.sizes.join(',')}" data-price="${p.price}" data-order="${i}"><div class="qa" aria-label="Quick add">${p.sizes.map(s => `<button data-size="${s}" class="${p.stock && p.stock[s] === 0 ? 'so' : ''}">${s}</button>`).join('')}</div><a class="card-img" href="/products/${p.id}/" aria-label="${esc(p.name)}"><img src="${img(p.images[0], 700)}" srcset="${srcset(p.images[0])}" sizes="(max-width:700px) 50vw, 25vw" width="700" height="875" alt="${esc(p.name)} – Humble Times Irish streetwear" loading="lazy">${p.images[1] ? `<img class="alt" src="${img(p.images[1], 700)}" alt="" loading="lazy">` : ''}${p.was ? '<span class="tag sale">Sale</span>' : p.new ? '<span class="tag">New in</span>' : ''}<span class="tag low" style="${totalStock(p) <= 8 ? '' : 'display:none'}">Low stock</span></a><div class="card-meta"><h3><a href="/products/${p.id}/">${esc(p.name)}</a><span class="sub">${esc(p.colour)}</span></h3>${priceHtml(p)}</div><button class="qa-m" aria-label="Quick add ${esc(p.name)}">+</button></article>`;
const productLd = p => ({ '@context': 'https://schema.org', '@type': 'ProductGroup', '@id': `${S.url}/products/${p.id}/#product`, name: p.name, url: `${S.url}/products/${p.id}/`, image: p.images.map(f => img(f, 1200)), description: p.desc.filter(d => !d.startsWith('PLACEHOLDER')).join(' '), brand: { '@type': 'Brand', name: S.short }, productGroupID: p.id, variesBy: ['https://schema.org/size'], color: p.colour, material: p.details[0], audience: { '@type': 'PeopleAudience', suggestedGender: 'unisex' },
  hasVariant: p.sizes.map(s => ({ '@type': 'Product', name: `${p.name} — ${s}`, sku: `${p.id}-${s}`, size: s, offers: { '@type': 'Offer', priceCurrency: 'EUR', price: p.price, priceValidUntil: new Date(Date.now() + 90 * 864e5).toISOString().slice(0, 10), availability: p.stock && p.stock[s] === 0 ? 'https://schema.org/OutOfStock' : 'https://schema.org/InStock', itemCondition: 'https://schema.org/NewCondition', url: `${S.url}/products/${p.id}/?size=${s}`, seller: { '@id': S.url + '/#org' }, shippingDetails: { '@type': 'OfferShippingDetails', shippingRate: { '@type': 'MonetaryAmount', value: S.shipIE, currency: 'EUR' }, shippingDestination: { '@type': 'DefinedRegion', addressCountry: 'IE' }, deliveryTime: { '@type': 'ShippingDeliveryTime', handlingTime: { '@type': 'QuantitativeValue', minValue: 1, maxValue: 2, unitCode: 'DAY' }, transitTime: { '@type': 'QuantitativeValue', minValue: 2, maxValue: 3, unitCode: 'DAY' } } }, hasMerchantReturnPolicy: { '@type': 'MerchantReturnPolicy', applicableCountry: 'IE', returnPolicyCategory: 'https://schema.org/MerchantReturnFiniteReturnWindow', merchantReturnDays: 30, returnMethod: 'https://schema.org/ReturnByMail', returnFees: 'https://schema.org/ReturnFeesCustomerResponsibility' } } })),
  ...(D.reviews.filter(r => r.product === p.id).length ? { aggregateRating: { '@type': 'AggregateRating', ratingValue: (D.reviews.filter(r => r.product === p.id).reduce((a, r) => a + r.stars, 0) / D.reviews.filter(r => r.product === p.id).length).toFixed(1), reviewCount: D.reviews.filter(r => r.product === p.id).length } } : {}) });
const faqHtml = list => `<div class="faq">${list.map(f => `<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</div>`;
const newsletter = () => `<section class="news"><div class="wrap news-grid"><div class="rv"><div class="lab mute">Newsletter</div><h2 class="h h-lg" style="margin-top:6px">Subscribe &amp; stay in the loop</h2><p class="p mute" style="margin-top:8px">News on drops, restocks and sales. Sign up and get 10% off your first order.</p></div><div class="rv"><form id="newsForm"><label class="sr" for="em">Email</label><input id="em" name="email" type="email" required placeholder="Email address"><button type="submit">Subscribe</button></form><div class="note">By subscribing you accept to receive commercial communications. See our <a href="/privacy/" style="text-decoration:underline">privacy policy</a>.</div></div></div></section>`;
const grid = (list, cls = '') => `<div class="grid ${cls} stagger">${list.map(card).join('')}</div>`;
const sh = (t, n, href, label = 'View all') => `<div class="wrap sh rv"><h2>${t}${n != null ? `<i>${n}</i>` : ''}</h2>${href ? `<a class="lnk" href="${href}">${label}</a>` : ''}</div>`;
const journalTeaser = () => `<section class="sec">${sh('Journal', null, '/journal/')}<div class="wrap jgrid stagger">${D.journal.slice(0, 2).map(j => `<a class="jcard" href="/journal/${j.slug}/"><img src="${img(j.img, 900)}" alt="${esc(j.title)}" loading="lazy"><time datetime="${j.date}">${fmtDate(j.date)}</time><h3>${esc(j.title)}</h3><p>${esc(j.excerpt)}</p></a>`).join('')}</div></section>`;
const reviewsHtml = list => list.length ? `<section class="sec">${sh('Reviews', list.length)}<div class="reviews stagger">${list.slice(0, 6).map(r => `<div class="review"><div class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5 - r.stars)}</div><p>“${esc(r.text)}”</p><small>${esc(r.name)}${r.where ? ', ' + esc(r.where) : ''} · ${esc(D.products.find(p => p.id === r.product)?.name || '')}</small></div>`).join('')}</div></section>` : '';

/* ---------- HOME ---------- */
{
  const j = D.products[0], news = D.products.filter(p => p.tags.includes('top-picks')), best = D.products.filter(p => !p.was);
  const body = `
<section class="hero" aria-label="Featured">
  <a href="/products/ht-jersey/"><img src="${img(j.images[1], 1400)}" srcset="${srcset(j.images[1])}" sizes="(max-width:700px) 100vw, 50vw" alt="The Jersey – Humble Times" fetchpriority="high" width="1400" height="1750"><div class="cap"><div><small>${esc(S.season)} · New in</small><b>The Jersey</b></div><span class="lnk">Shop now</span></div></a>
  <a href="/collections/hoodies/"><img src="${img(D.collections.hoodies.img, 1400)}" srcset="${srcset(D.collections.hoodies.img)}" sizes="(max-width:700px) 100vw, 50vw" alt="Hoodies – Humble Times" width="1400" height="1750" loading="lazy"><div class="cap"><div><small>Heavyweight</small><b>Hoodies</b></div><span class="lnk">Shop now</span></div></a>
</section>
<section class="sec">${sh('New arrivals', news.length, '/collections/top-picks/')}${grid(news)}</section>
<section class="band"><img src="${img(D.hero, 1800)}" srcset="${img(D.hero, 900)} 900w, ${img(D.hero, 1800)} 1800w" sizes="100vw" alt="Humble Times campaign, Wexford" loading="lazy"><div class="cap"><small>Worn in Wexford</small><b>Everyday Irish streetwear</b></div></section>
<section class="sec">${sh('Best sellers', 'all time', '/shop/')}${grid(best, 'row')}</section>
<section class="sec" style="padding-bottom:0">${sh('Shop by category')}<div class="index rv">${[['hoodies', '01'], ['outerwear', '02'], ['pants', '03'], ['clearance', '04']].map(([k, n]) => `<a href="/collections/${k}/"><small>${n}</small><span>${esc(D.collections[k].name)}</span><span>${count(k)} item${count(k) > 1 ? 's' : ''}</span><img class="pv" src="${img(D.collections[k].img, 400)}" alt="" loading="lazy"></a>`).join('')}</div></section>
<section class="sec">${sh('Shop all', D.products.length, '/shop/')}${grid(D.products)}</section>
${reviewsHtml(D.reviews)}
<section class="sec">${sh('@humbletimesapparel', null, S.instagram, 'Follow')}<div class="ig stagger">${D.lookbook.slice(0, 6).map((f, i) => `<a href="${S.instagram}" target="_blank" rel="noopener"><img src="${img(f, 600)}" alt="Humble Times on Instagram ${i + 1}" loading="lazy"></a>`).join('')}</div></section>
${journalTeaser()}
<section class="sec">${sh('Good to know', null, '/faq/', 'All FAQs')}<div class="wrap rv">${faqHtml(D.faq.slice(0, 4))}</div></section>
${newsletter()}`;
  write('index.html', shell({ title: `${S.name} | Irish Streetwear from Wexford – Hoodies, Jerseys & Essentials`, desc: S.description, url: '/', body, ogImage: img(D.hero, 1200), jsonld: [faqLd(D.faq.slice(0, 4)), { '@context': 'https://schema.org', '@type': 'WebPage', '@id': S.url + '/#home', speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.faq'] } }, { '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: D.products.map((p, i) => ({ '@type': 'ListItem', position: i + 1, url: `${S.url}/products/${p.id}/` })) }] }));
}

/* ---------- COLLECTIONS ---------- */
function collectionPage(slug, c, list) {
  const url = slug ? `/collections/${slug}/` : '/shop/';
  const body = `<div class="wrap"><div class="crumbs"><a href="/">Home</a> / ${slug ? '<a href="/shop/">Shop</a> / ' : ''}${esc(c.name)}</div><div class="coll-head"><h1 class="rv">${esc(c.h1)}<i>${list.length}</i></h1><p class="rv">${esc(c.blurb)}</p></div></div>
<div class="bar" id="filters"><span class="lab mute" style="margin-right:6px">Size</span><button class="chip" data-size="">All</button>${['XS', 'S', 'M', 'L', 'XL', '2XL'].map(s => `<button class="chip" data-size="${s}">${s}</button>`).join('')}<label class="sr" for="sort">Sort</label><select id="sort"><option value="featured">Sort: Featured</option><option value="low">Price ↑</option><option value="high">Price ↓</option><option value="new">Newest</option></select></div>
<div class="grid stagger" id="collGrid">${list.map(card).join('')}</div><div class="empty" id="empty" style="display:none">Nothing in that size right now — join the restock list below.</div>
<div class="wrap seo-copy rv"><h2>${esc(c.name)} from an Irish streetwear brand</h2><p>Every piece is designed in Co. Wexford and shipped from Ireland within 1–2 working days. Delivery is €${S.shipIE} nationwide and free on orders over €${S.freeShip}, with tracked delivery to the UK and EU. Unworn items can be returned within 30 days.</p></div>
${newsletter()}`;
  write(url + 'index.html', shell({ title: c.seoTitle, desc: `${c.blurb} Irish streetwear from Humble Times, Co. Wexford. Free delivery in Ireland over €${S.freeShip}.`, url, body, ogImage: img(c.img, 1200), jsonld: [crumbs([['Home', '/'], [c.name, url]]), { '@context': 'https://schema.org', '@type': 'CollectionPage', name: c.name, url: S.url + url, mainEntity: { '@type': 'ItemList', itemListElement: list.map((p, i) => ({ '@type': 'ListItem', position: i + 1, url: `${S.url}/products/${p.id}/`, name: p.name })) } }] }));
}
collectionPage(null, { name: 'Shop all', h1: 'All products', blurb: 'Everything we make, in one place.', seoTitle: 'Shop All – Irish Streetwear Hoodies, Jerseys & Joggers | Humble Times', img: D.hero }, D.products);
Object.entries(D.collections).forEach(([k, c]) => collectionPage(k, { ...c, h1: k === 'top-picks' ? 'New arrivals' : c.h1 }, D.products.filter(p => p.tags.includes(k))));

/* ---------- PRODUCTS ---------- */
D.products.forEach(p => {
  const url = `/products/${p.id}/`, rel = D.products.filter(x => x.id !== p.id && x.tags.some(t => p.tags.includes(t))).slice(0, 4);
  const faqs = [...p.faq, ...D.faq.slice(1, 3)]; const coll = p.tags.find(t => D.collections[t]); const revs = D.reviews.filter(r => r.product === p.id);
  const body = `<div class="wrap crumbs"><a href="/">Home</a> / <a href="/shop/">Shop</a> / <a href="/collections/${coll || 'top-picks'}/">${esc(D.collections[coll]?.name || 'Shop')}</a> / ${esc(p.name)}</div>
<div class="pdp">
  <div class="gal">${p.images.map((f, i) => `<img src="${img(f, 1400)}" srcset="${srcset(f)}" sizes="(max-width:900px) 100vw, 30vw" width="1400" height="1750" alt="${esc(p.name)} by Humble Times – ${i === 0 ? 'front' : 'view ' + (i + 1)}" ${i ? 'loading="lazy"' : 'fetchpriority="high"'}>`).join('')}</div>
  <div class="buy">
    <div class="lab" style="color:var(--acc)">${p.was ? 'Sale' : p.new ? 'New in' : esc(S.season)}</div>
    <h1 style="margin-top:6px">${esc(p.name)}</h1>${priceHtml(p)}
    ${revs.length ? `<div class="stars" style="margin:-10px 0 12px">${'★'.repeat(Math.round(revs.reduce((a, r) => a + r.stars, 0) / revs.length))} <span class="mute" style="letter-spacing:0;font-size:11px">${revs.length} review${revs.length > 1 ? 's' : ''}</span></div>` : ''}
    <div class="kv"><span>Colour</span><span class="mute" style="text-transform:none;letter-spacing:0;font-size:12px">${esc(p.colour)}</span></div>
    <div class="kv"><span>Size</span><span><a href="/size-guide/" data-modal>Size guide</a> · <button data-quiz>Fit quiz</button></span></div>
    <div class="sizes" id="sizes">${p.sizes.map(s => `<button data-size="${s}" aria-pressed="false" class="${p.stock && p.stock[s] === 0 ? 'so' : ''}">${s}</button>`).join('')}</div>
    <p class="fit" id="fitrec"></p>${p.fit ? `<p class="fit">${esc(p.fit)}</p>` : ''}
    <div class="err" id="err" aria-live="polite"></div>
    <div class="notify" id="notify"><form id="notifyForm" style="display:contents"><label class="sr" for="ne">Email for restock</label><input id="ne" name="email" type="email" required placeholder="Email me when it's back"><button class="btn" type="submit">Notify me</button></form></div>
    <div style="display:flex;gap:8px;align-items:center;margin-top:14px"><span class="lab mute">Qty</span><span class="qty"><button aria-label="Decrease quantity" id="qm">−</button><output id="qo">1</output><button aria-label="Increase quantity" id="qp">+</button></span></div>
    <button class="btn full" id="addBtn" data-id="${p.id}">Add to cart · ${eur(p.price)}</button>
    <div class="deliv" id="deliv"><b>Ships from Co. Wexford in 1–2 working days</b><span>An Post tracked · free over €${S.freeShip} · 30-day returns</span></div>
    <div class="desc">${p.desc.filter(d => !d.startsWith('PLACEHOLDER')).map(d => `<p>${esc(d)}</p>`).join('')}</div>
    <div class="acc">
      <details><summary>Details &amp; composition</summary><ul>${p.details.map(d => `<li>${esc(d)}</li>`).join('')}</ul></details>
      <details><summary>Fit &amp; sizing</summary><p>Available in ${p.sizes[0]}–${p.sizes.at(-1)}. Relaxed fit — size down for a closer fit. ${p.fit ? esc(p.fit) + '.' : ''}</p></details>
      <details><summary>Care</summary><p>${esc(p.care)}</p></details>
      <details><summary>Shipping &amp; returns</summary><p>Ships from Ireland within 1–2 working days. €${S.shipIE} in Ireland, free over €${S.freeShip}; UK and EU tracked from ${eur(S.shipEU)}. Unworn items can be returned within 30 days.</p></details>
    </div>
    ${p.pairs?.length ? `<div class="pair"><h3>Complete the look</h3><div class="pair-row">${p.pairs.map(id => D.products.find(x => x.id === id)).filter(Boolean).map(x => `<a href="/products/${x.id}/" data-qa="${x.id}"><img src="${img(x.images[0], 200)}" alt=""><span><b>${esc(x.name)}</b>${eur(x.price)} · <u>Quick add</u></span></a>`).join('')}</div></div>` : ''}
  </div>
</div>
${revs.length ? `<section class="sec">${sh('Reviews', revs.length)}<div class="reviews stagger">${revs.map(r => `<div class="review"><div class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5 - r.stars)}</div><p>“${esc(r.text)}”</p><small>${esc(r.name)}${r.where ? ', ' + esc(r.where) : ''}</small></div>`).join('')}</div></section>` : ''}
${faqs.length ? `<section class="sec">${sh('Questions')}<div class="wrap rv">${faqHtml(faqs)}</div></section>` : ''}
${rel.length ? `<section class="sec">${sh('You may also like', null, '/shop/')}${grid(rel, 'row')}</section>` : ''}
<div class="sticky-buy" id="stickyBuy"><div><b>${esc(p.name)}</b><br><span id="stickySize" class="mute" style="font-size:11px">Choose a size</span></div><button class="btn" id="stickyAdd">Add · ${eur(p.price)}</button></div>`;
  write(url + 'index.html', shell({ title: p.seoTitle, desc: p.seoDesc, url, body, type: 'product', chips: false, ogImage: img(p.images[0], 1200), jsonld: [productLd(p), crumbs([['Home', '/'], ['Shop', '/shop/'], [p.name, url]]), ...(faqs.length ? [faqLd(faqs)] : [])] }));
});

/* ---------- JOURNAL ---------- */
write('/journal/index.html', shell({ title: 'Journal – Style, Fit & Fabric from Humble Times Ireland', desc: 'Styling guides, fit advice and stories from an Irish streetwear brand in Co. Wexford.', url: '/journal/', recent: false, body: `<div class="wrap"><div class="about-hero"><div class="lab mute rv">Journal</div><h1 class="h h-xl rv" style="margin-top:8px">Notes from Wexford</h1></div><div class="jgrid stagger" style="padding-bottom:64px">${D.journal.map(j => `<a class="jcard" href="/journal/${j.slug}/"><img src="${img(j.img, 900)}" alt="${esc(j.title)}" loading="lazy"><time datetime="${j.date}">${fmtDate(j.date)}</time><h3>${esc(j.title)}</h3><p>${esc(j.excerpt)}</p></a>`).join('')}</div></div>${newsletter()}`, jsonld: [crumbs([['Home', '/'], ['Journal', '/journal/']]), { '@context': 'https://schema.org', '@type': 'Blog', name: 'The Humble Times Journal', publisher: { '@id': S.url + '/#org' } }] }));
D.journal.forEach(j => { const url = `/journal/${j.slug}/`; write(url + 'index.html', shell({ title: `${j.title} | Humble Times Journal`, desc: j.excerpt, url, type: 'article', ogImage: img(j.img, 1200), recent: false, chips: false, body: `<article class="wrap"><div class="article" style="padding-bottom:0"><div class="crumbs" style="padding-left:0"><a href="/">Home</a> / <a href="/journal/">Journal</a></div><time class="lab mute" datetime="${j.date}">${fmtDate(j.date)}</time><h1 class="rv">${esc(j.title)}</h1><p class="rv mute" style="font-size:16px">${esc(j.excerpt)}</p></div><div class="article cover rv" style="padding:0"><img src="${img(j.img, 1400)}" alt="${esc(j.title)}"></div><div class="article" style="padding-top:0">${j.body.map(p => `<p class="rv">${md(p)}</p>`).join('')}<p class="rv" style="margin-top:24px"><a class="btn" href="/shop/">Shop the range</a></p></div></article>${newsletter()}`, jsonld: [crumbs([['Home', '/'], ['Journal', '/journal/'], [j.title, url]]), { '@context': 'https://schema.org', '@type': 'Article', headline: j.title, description: j.excerpt, image: img(j.img, 1200), datePublished: j.date, dateModified: j.date, author: { '@id': S.url + '/#org' }, publisher: { '@id': S.url + '/#org' }, mainEntityOfPage: S.url + url, inLanguage: 'en-IE' }] })); });

/* ---------- INFO ---------- */
const infoPage = (slug, title, seoTitle, desc, inner, extraLd = []) => write(`/${slug}/index.html`, shell({ title: seoTitle, desc, url: `/${slug}/`, recent: false, body: `<div class="wrap"><div class="crumbs"><a href="/">Home</a> / ${esc(title)}</div><div class="page"><h1 class="rv">${title}</h1><div class="rv">${inner}</div></div></div>`, jsonld: [crumbs([['Home', '/'], [title, `/${slug}/`]]), ...extraLd] }));
write('/about/index.html', shell({ title: `About Humble Times – Irish Streetwear Brand from Wexford`, desc: `Humble Times Apparel is an independent Irish streetwear brand from Co. Wexford, built on quality, comfort and timeless design.`, url: '/about/', recent: false, body: `<div class="wrap"><div class="about-hero"><div class="lab mute rv">About</div><h1 class="h h-xl rv" style="margin-top:8px">${esc(D.about.h1)}</h1><p class="p rv" style="margin-top:16px;font-size:16px">${esc(D.about.lede)}</p></div></div><section class="band"><img src="${img(D.storyImg, 1800)}" alt="Humble Times, Wexford, Ireland" loading="lazy"></section><div class="wrap"><div class="page">${D.about.body.map(p => `<p class="rv" style="font-size:16px">${esc(p)}</p>`).join('')}<h2 class="rv">At a glance</h2><ul class="rv"><li><strong>Who:</strong> Independent Irish streetwear brand, Humble Times Apparel</li><li><strong>Where:</strong> Designed and shipped from Co. Wexford, South East Ireland</li><li><strong>What:</strong> Heavyweight hoodies, The Jersey, The Windbreaker, joggers and essentials</li><li><strong>Delivery:</strong> €${S.shipIE} in Ireland, free over €${S.freeShip}; tracked UK &amp; EU</li><li><strong>Returns:</strong> 30 days on unworn items</li><li><strong>Find us:</strong> <a href="${S.instagram}" style="text-decoration:underline">Instagram</a> · <a href="${S.tiktok}" style="text-decoration:underline">TikTok</a></li></ul><p class="rv" style="margin-top:24px"><a class="btn" href="/shop/">Shop the range</a></p></div></div>${newsletter()}`, jsonld: [crumbs([['Home', '/'], ['About', '/about/']]), { '@context': 'https://schema.org', '@type': 'AboutPage', mainEntity: { '@id': S.url + '/#org' }, speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.about-hero p', '.page ul'] } }] }));
infoPage('faq', 'FAQs &amp; contact', 'FAQ – Delivery, Returns, Sizing | Humble Times Ireland', 'Answers on Irish delivery times, UK/EU shipping, returns, hoodie fit and payment at Humble Times Apparel.', faqHtml(D.faq) + `<p style="margin-top:24px">Still stuck? <a href="/contact/" class="lnk">Contact us</a></p>`, [faqLd(D.faq)]);
infoPage('shipping', 'Shipping policy', 'Delivery in Ireland, UK & EU | Humble Times', `Humble Times ships from Co. Wexford within 1–2 working days. €${S.shipIE} delivery in Ireland, free over €${S.freeShip}. Tracked UK and EU delivery from €${S.shipEU}.`, `<p>All orders ship from Co. Wexford, Ireland within 1–2 working days of payment. Order before ${S.cutoffHour - 12}pm on a working day and it ships the same day.</p><h2>Ireland</h2><p>An Post tracked delivery ${eur(S.shipIE)}, <strong>free on orders over €${S.freeShip}</strong>. Usually 2–3 working days.</p><h2>UK &amp; EU</h2><p>Tracked delivery from ${eur(S.shipEU)}, typically 4–7 working days. UK orders may be subject to customs charges on arrival.</p><h2>Rest of world</h2><p>Rates and estimated delivery are calculated at checkout.</p><p><em>PLACEHOLDER — replace with your current policy if it differs.</em></p>`);
infoPage('returns', 'Returns &amp; exchanges', 'Returns & Exchanges | Humble Times', '30-day returns on unworn Humble Times items with tags attached. How to start a return or exchange.', `<p>Unworn items with tags attached can be returned within 30 days of delivery for a refund or exchange. Return postage is covered by the customer unless the item is faulty.</p><p>Email <a href="mailto:${S.email}" style="text-decoration:underline">${S.email}</a> with your order number to start a return.</p><p><em>PLACEHOLDER — replace with your current refund policy.</em></p>`);
infoPage('size-guide', 'Size guide', 'Size Guide – Hoodies & The Jersey | Humble Times', 'Garment measurements for Humble Times hoodies, The Jersey, The Windbreaker and joggers. Relaxed, oversized fits — size down for a closer fit.', `<p>Measurements are garment measurements in cm, laid flat. All fits are relaxed.</p><h2>Hoodies &amp; The Jersey</h2>${sizeTable()}<p><a href="#" class="lnk" data-quiz>Not sure? Take the fit quiz</a></p><p><em>PLACEHOLDER — update with your real measurements.</em></p>`);
infoPage('contact', 'Contact', 'Contact Humble Times Apparel, Wexford', 'Get in touch with Humble Times about orders, sizing, returns or collaborations. We reply within one working day.', `<p>Questions about an order, sizing or a collab? We reply within one working day.</p><p>Email <a href="mailto:${S.email}" style="text-decoration:underline">${S.email}</a> or DM us on <a href="${S.instagram}" target="_blank" rel="noopener" style="text-decoration:underline">Instagram</a>.</p><form id="contactForm"><label class="sr" for="cn">Name</label><input id="cn" name="cn" placeholder="Name" required><label class="sr" for="ce">Email</label><input id="ce" name="ce" type="email" placeholder="Email" required><label class="sr" for="cm">Message</label><textarea id="cm" name="cm" rows="5" placeholder="How can we help?" required></textarea><button class="btn" type="submit">Send message</button></form>`, [{ '@context': 'https://schema.org', '@type': 'ContactPage', mainEntity: { '@id': S.url + '/#org' } }]);
infoPage('privacy', 'Privacy policy', 'Privacy Policy | Humble Times', 'How Humble Times Apparel handles your personal data.', `<p>PLACEHOLDER — paste your privacy policy here. Payments are processed by Stripe; full card details never reach our servers.</p>`);
infoPage('terms', 'Terms &amp; conditions', 'Terms & Conditions | Humble Times', 'Terms of service for purchases from Humble Times Apparel.', `<p>PLACEHOLDER — paste your terms here.</p>`);
write('/thanks/index.html', shell({ title: 'Thank you | Humble Times', desc: 'Order confirmed.', url: '/thanks/', recent: false, chips: false, body: `<div class="wrap"><div class="page" style="margin:0 auto;text-align:center"><h1>Go raibh maith agat</h1><p>Your order is in. A confirmation is on its way to your inbox and it'll ship from Wexford within 1–2 working days.</p><div id="orderSummary" style="margin:20px auto 28px;padding:16px;border:1px solid var(--line);text-align:left;max-width:400px;font-size:13px"></div><a class="btn" href="/shop/">Continue shopping</a></div></div>` }));
write('/404.html', shell({ title: 'Page not found | Humble Times', desc: '', url: '/404.html', recent: false, body: `<div class="wrap"><div class="page"><h1>Page not found</h1><p>That link doesn't go anywhere. <a class="lnk" href="/shop/">Back to the shop</a></p></div></div>` }));

/* ---------- static ---------- */
fs.copyFileSync('src/site.css', path.join(OUT, 'site.css')); fs.copyFileSync('src/site.js', path.join(OUT, 'site.js'));
write('favicon.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" fill="#111"/><text x="32" y="43" text-anchor="middle" font-family="Arial" font-weight="700" font-size="28" fill="#fff" letter-spacing="1">HT</text></svg>`);
const urls = ['/', '/shop/', '/about/', '/journal/', '/faq/', '/shipping/', '/returns/', '/size-guide/', '/contact/', ...Object.keys(D.collections).map(k => `/collections/${k}/`), ...D.products.map(p => `/products/${p.id}/`), ...D.journal.map(j => `/journal/${j.slug}/`)];
const today = new Date().toISOString().slice(0, 10);
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urls.map(u => { const p = D.products.find(x => u === `/products/${x.id}/`); return `<url><loc>${S.url}${u}</loc><lastmod>${today}</lastmod><changefreq>${u === '/' ? 'weekly' : 'monthly'}</changefreq><priority>${u === '/' ? '1.0' : p ? '0.9' : '0.6'}</priority>${p ? p.images.map(f => `<image:image><image:loc>${esc(img(f, 1200))}</image:loc><image:title>${esc(p.name)}</image:title></image:image>`).join('') : ''}</url>`; }).join('\n')}\n</urlset>`);
write('robots.txt', `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /thanks/\n\nUser-agent: GPTBot\nAllow: /\nUser-agent: PerplexityBot\nAllow: /\nUser-agent: ClaudeBot\nAllow: /\nUser-agent: Google-Extended\nAllow: /\n\nSitemap: ${S.url}/sitemap.xml\n`);
write('llms.txt', `# ${S.name}\n\n> ${S.description}\n\nHumble Times Apparel is an independent Irish streetwear brand based in Co. Wexford, South East Ireland. All orders ship from Wexford within 1–2 working days (same day before ${S.cutoffHour - 12}pm). Delivery in Ireland is €${S.shipIE} and free over €${S.freeShip}; tracked UK/EU delivery from €${S.shipEU}. 30-day returns on unworn items. Prices in EUR including VAT.\n\n## Products\n${D.products.map(p => `- [${p.name}](${S.url}/products/${p.id}/): ${p.blurb} ${eur(p.price)}${p.was ? ` (was ${eur(p.was)})` : ''}, sizes ${p.sizes.join('/')}.`).join('\n')}\n\n## Collections\n${Object.entries(D.collections).map(([k, c]) => `- [${c.name}](${S.url}/collections/${k}/): ${c.blurb}`).join('\n')}\n\n## Journal\n${D.journal.map(j => `- [${j.title}](${S.url}/journal/${j.slug}/): ${j.excerpt}`).join('\n')}\n\n## Help\n- [FAQ](${S.url}/faq/)\n- [Shipping](${S.url}/shipping/)\n- [Returns](${S.url}/returns/)\n- [Size guide](${S.url}/size-guide/)\n- [About](${S.url}/about/)\n- [Contact](${S.url}/contact/)\n\n## FAQ\n${D.faq.map(f => `Q: ${f.q}\nA: ${f.a}`).join('\n\n')}\n`);
write('_redirects', `/pages/contact /contact/ 301\n/pages/about /about/ 301\n/policies/shipping-policy /shipping/ 301\n/policies/refund-policy /returns/ 301\n/policies/privacy-policy /privacy/ 301\n/policies/terms-of-service /terms/ 301\n/collections/all /shop/ 301\n/collections /shop/ 301\n/products /shop/ 301\n/search /shop/ 301\n/blogs/* /journal/ 301\n/account /shop/ 302\n/cart /shop/ 302\n`);
write('_headers', `/*\n  X-Content-Type-Options: nosniff\n  X-Frame-Options: SAMEORIGIN\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Strict-Transport-Security: max-age=31536000; includeSubDomains\n/site.css\n  Cache-Control: public, max-age=86400\n/site.js\n  Cache-Control: public, max-age=86400\n/api/*\n  Cache-Control: no-store\n`);
fs.cpSync(path.join(__dirname, 'functions'), path.join(OUT, 'functions'), { recursive: true });
console.log(`Built ${urls.length + 3} pages → dist/`);
